### ISSUE TITLE
Memory Leak. Can make TapWithDataRecognizer.from weak?

### ISSUE THREAD

**Issue by vfumin** [michaelhenry/ImageViewer.swift#102]
After 
`imageView.setupImageViewer(options: [.closeIcon(R.image.icnNavX()!)], from: parentVC)`
Where parentVC - UIViewController, and after closing viewController, it isn't free, because gesture strong hold reference parentVC

**Comment by michaelhenry** [comment]
@vfumin confirmed. Thanks for this report. I have now solved the issue with this PR #103.

I also made some adjustments that will prevent from passing the `RightNavItemDelegate` (which still referencing to self-view-controller in most cases) to just use a closure instead.  

Thanks
