### ISSUE TITLE
Cocoapods error message

### ISSUE THREAD

**Issue by chienplee** [michaelhenry/ImageViewer.swift#105]
The latest `pod 'ImageViewer.swift', '~> 3.0'` will lead to 

> [!] Unable to find a specification named `ImageViewer.swift/none` in `ImageViewer.swift (3.3.2)`.

Any solutions? Thanks in advance.

**Comment by michaelhenry** [comment]
@chienplee please try `3.2.2` 

and using `pod install --repo-update` 

Cheers,

**Comment by chienplee** [comment]
Still getting the same message

> [!] CocoaPods could not find compatible versions for pod "ImageViewer.swift":
  In Podfile:
    ImageViewer.swift (~> 3.2.2)

>None of your spec sources contain a spec satisfying the dependency: `ImageViewer.swift (~> 3.2.2)`.

**Comment by michaelhenry** [comment]
I think you just have to update your local pod repo so that the updated version will be there.

**Comment by chienplee** [comment]
Thanks, I'll close this for now and at the same time try to find out whats wrong with my cocoapods.
