### ISSUE TITLE
New transition animation shows duplicate image during transition

### ISSUE THREAD

**Issue by ericpapamarcos** [michaelhenry/ImageViewer.swift#106]
Thanks for this excellent library!

I noticed that #104 changed the transition animation.

This screen grab (from iOS 14) shows the transition from your example app after clicking on the cat in the top left corner:

![ImageViewer](https://user-images.githubusercontent.com/282771/94389041-95854180-0103-11eb-9f47-6d4fcce8e87d.png)
The updated transition appears to simultaneously fade out the original image, translate the original image to its new location, and also fade in a *second* image at the new location in the middle of the screen. The end result is that two images appear on screen during the transition which appears a little glitchy compared to the previous experience.

I've also noticed an issue where the image completely disappears during the transition where the original image fades out, but the second image doesn't fade in.

Can you please fix the transition to not duplicate the image?

**Comment by michaelhenry** [comment]
@ericpapamarcos thanks for the report. I will look into it.

**Comment by michaelhenry** [comment]
@ericpapamarcos please check [v3.3.3](https://github.com/michaelhenry/ImageViewer.swift/releases/tag/3.3.3) thanks

**Comment by ericpapamarcos** [comment]
This fixes the animation issue!

However, I'm still consistently seeing the new issue where the image completely disappears after the transition is complete. I've tried both `.theme(.light)` and `.theme(.dark)` and the issue repros consistently for both modes. (The issue repros consistently on device for me, but less so in the simulator.)

Is the code setting the opacity back to 0 when it's finished animating in some case?

**Comment by michaelhenry** [comment]
@ericpapamarcos i will check it. Thanks
