### ISSUE TITLE
With [URL]  work in the simulator but doesn't work in iPhone 11 pro device

### ISSUE THREAD

**Issue by maziar** [michaelhenry/ImageViewer.swift#122]
With [URL]  work in the simulator but doesn't work in the "iPhone 11 pro" phisical device

**Comment by michaelhenry** [comment]
I haven’t  check it yet.may I know what does the debugger  says? Thanks

**Comment by maziar** [comment]
I solved this issue by adding the image view to the cell content view,
the solution was very simple but the problem recognition was very time-consuming.
a view added above of image view and tap gesture of image view doesn't work in iPhone devices, not in the simulator.
anyway, the problem is solved.
