### ISSUE TITLE
Animations bug fix

### ISSUE THREAD

**Issue by filipealva** [michaelhenry/ImageViewer.swift#124]
Hey @michaelhenry, 

Thanks for the great work in this repo. We are looking forward to integrate it into our project, but we need this PR: https://github.com/michaelhenry/ImageViewer.swift/pull/113 to be merged first.

Can you please take a look on it? 

One of our team's member which is familiar with the code of the lib can help reviewing if you think it would be useful.

**Comment by michaelhenry** [comment]
Hi @filipealva , I apologize if i missed that pr. Other reviewers is also really helpful. I’ll take a look at it. Thank you

**Comment by filipealva** [comment]
Thank you for taking a look at it! I know how hard is to keep up with open source projects, really appreciate that 🙏


@thomasdelgado is there something you can do to help us reviewing or suggesting improvements on that PR?

Thank you guys

**Comment by michaelhenry** [comment]
@filipealva merged. please check thank you.

**Comment by filipealva** [comment]
Awesome, thank you!
