### ISSUE TITLE
Issue with Remote URLs

### ISSUE THREAD

**Issue by asolanki-in** [michaelhenry/ImageViewer.swift#127]
I have implemented it using tableview and using SDWebimage to implement it remote image.

When I tap on image in table cell it is opening detail image with transition but after appearing for 2-3 sec image goes blank and appear again. I think till remote image is loading it should show SDWebImage from table cell till High quality image loading.

You can re generate it on slow internet.

**Comment by michaelhenry** [comment]
@asolanki-in thank you for the report, I'll take a look at it.

**Comment by ErAshu** [comment]
Any Update on this?

**Comment by ErAshu** [comment]
In my case, i am using Kingfisher for image fetching from url with Placeholder image. When i tap on image, the image open with transition but after appearing for 1 sec, image goes blank with Placeholder image.

**Comment by Razanajam** [comment]
Yes, there is no caching used inside app, that why this issue occurs.

**Comment by asolanki-in** [comment]
@michaelhenry  I still facing this issue, can you check below video. Still when detail image is opening is gets blinked between.

https://imgur.com/a/AaFfASa
