### ISSUE TITLE
Imageview in tableview cell

### ISSUE THREAD

**Issue by rursache** [michaelhenry/ImageViewer.swift#86]
Looks like if i call `setupImageViewer()` on imageviews in a tableview cell, it does not work

**Comment by rursache** [comment]
EDIT: my bad, it was an issue with the way this extension presents views, see https://github.com/michaelhenry/ImageViewer.swift/issues/87

**Comment by maulik3107** [comment]
While loading new image first time it's not work after we back from view second time it's work perfectly.
