### ISSUE TITLE
Cannot specify the VC to present from

### ISSUE THREAD

**Issue by rursache** [michaelhenry/ImageViewer.swift#87]
Cannot specify the VC to present from

**Comment by michaelhenry** [comment]
@rursache that's a good question, I think a good way to add it is by adding an optional parameter for the VC that will override the [keyWindow.rootViewController](https://github.com/michaelhenry/ImageViewer.swift/blob/de436e1ccf9f90ae63a71a1481a7872831107086/Sources/UIImageView_Extensions.swift#L12) 

what do you think? thanks

**Comment by rursache** [comment]
hey!
for the moment i created a new class:
```
class ImageViewerExt: UIImageView {
	var customVC: UIViewController?
}
```
a new init func:
```
public func setupImageViewer(presentFrom: UIViewController) {
		self.customVC = presentFrom
		self.setupImageViewer()
	}
```
and changed `showImageViewer` to use `customVC` if not nil

**Comment by michaelhenry** [comment]
@rursache in `v3.0.10`, i now added `from:UIViewController`. please see this commit  995162bc5f4a8ab0d1eda419bb465aaa08adb8f0 . thanks
