### ISSUE TITLE
showImageViewer can not create ImageCarouselViewController on presented navigation controller

### ISSUE THREAD

**Issue by arindavoodian** [michaelhenry/ImageViewer.swift#88]
.create() method in UIImageView_Extensions.swift attempts to present on vc from rootViewController.

Since there is a presented view already in my project where I'm calling ImageViewer, the call errors with:

<ImageViewer_swift.ImageCarouselViewController: 0x7fd0aa9aa000> on <Project.RootViewController: 0x7fd0a9411960> whose view is not in the window hierarchy!

Is there a way around this?

**Comment by michaelhenry** [comment]
@arindavoodian thanks for the report. I now fixed it on `v3.0.10`. Thanks

**Comment by arindavoodian** [comment]
Thanks!
