### ISSUE TITLE
Make dependency from SDWebImage clear

### ISSUE THREAD

**Issue by pmanna** [michaelhenry/ImageViewer.swift#91]
There's no mention that SDWebImage is a requirement: it's not added as a submodule, nor is clarified in the description/Readme of the Github project.
Not a major issue, still it's been time-consuming trying to integrate it, only to discover at compile time that it won't work…

**Comment by michaelhenry** [comment]
@pmanna thank you so much for this. Yes, you’re right. I will update it. Thanks
