### ISSUE TITLE
Can it be used in SwiftUI project?

### ISSUE THREAD

**Issue by ilant** [michaelhenry/ImageViewer.swift#94]
Hi, is there any way to use the library in SwiftUI?

**Comment by anushkmittal** [comment]
bump. @ilant were you able to use it?

**Comment by ilant** [comment]
> bump. @ilant were you able to use it?

hi, I finally used the SKPhotobrowser library as photo viewer, the way it is shown here - https://stackoverflow.com/questions/61483839/swiftui-type-does-not-conform-to-protocol-uiviewrepresentable

To add the cocoapods to swiftui project, you can see this one - https://www.youtube.com/watch?v=Me62H3PSvJs
