### ISSUE TITLE
Please add carthage support

### ISSUE THREAD

**Issue by oscardemoya** [michaelhenry/ImageViewer.swift#96]

**Comment by michaelhenry** [comment]
Hi @oscardemoya, currently I'm busy but I would happy to accept PR for this. thank you.

**Comment by bdjessup** [comment]
I am [attempting to add support for Swift package manager](https://github.com/michaelhenry/ImageViewer.swift/pull/100), maybe that would be relevant.

**Comment by oscardemoya** [comment]
> Hi @oscardemoya, sorry. currently I'm so busy but I would happy to accept PR for this. thank you.

Hi @michaelhenry, I just submitted [this PR](https://github.com/michaelhenry/ImageViewer.swift/pull/101) which adds support for Carthage.

**Comment by michaelhenry** [comment]
Thanks @oscardemoya
