### ISSUE TITLE
Always getting small size image in right side of the screen

### ISSUE THREAD

**Issue by ramesh09ios** [michaelhenry/ImageViewer.swift#98]
Hi ImageView is really very nice to use but i am facing an issue on second image when swipe to right.

Steps:
1. I was implemented a TaleViewCell contain Collection view.In collection view "cellForRowAt:indexPath" have "setupImageViewer"

All devices it shows a small image on right side Please find attached image. 
![01](https://user-images.githubusercontent.com/17927941/87927889-8baae680-caa1-11ea-9578-ef1f72029e2d.png)

**Comment by michaelhenry** [comment]
@ramesh09ios I think this should be fixed by v`3.2.2`. Please check it. thanks

**Comment by stephendanielxxx** [comment]
Hi, this issue also happened to me, I use the 3.3.6 version, is there any way to solve this issue?
